#!/bin/bash
printf "%s\n" "$(echo "$WATER" | tr 'water' '01234') $(echo "$STIR" | tr 'stir.' '01234')" | tr -d ' ' | ( read a b c d e; printf "%s\n" "$((a*125+ b*25 + c*5 + d))" | tr '0123456789' 'bestchol' )
